[package]
name = "nbabel-rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static-math = "0.2.2"

# [profile.release]
# debug = true
